# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f130a5d93f1f1760473a7e2e1c5b63656774dbc5538acf653c72641cf9527e9263f36e19725dc5530b351565cb1b7adac31e500f118a7e0427c6b4c8539c44a4

test:
  secret_key_base: 1f0d1a8141328ccdc9e9f84777258393c3b7de62ed06dbe2f1c10dca498b67aa0f69885fa79ca9c84a7ba1bab6b50f3fefcd11b7f10980a439d2d8d5cea51140

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
